openapi: 3.0.1
info:
  title: Analytics Core API Specs for Version 2
  version: '2.2'
servers:
- url: https://f8a-analytics-2445582058137.production.gw.apicast.io/api/v2
  description: "Dependency Analytics Server"
security:
- tokenAuth: []
paths:
  /get-token/:
    get:
      tags:
        - 3-Scale token
      summary: Get 3-scale token and url with higher rate limit.
      responses:
        200:
          description: Hihger rate 3-scale key and url
          content:
            application/json:
              schema:
                type: object
                items:
                  anyOf:
                    - $ref: '#/components/schemas/Higher-rate-3scale'
              examples:
                default:
                  $ref: '#/components/examples/higher-rate-3scale'

        401:
          description: Request unauthorized
          content: {}
        404:
          description: Endpoint not found
          content: {}

  /vulnerability-analysis/:
    post:
      tags:
        - CA batch call
      summary: Get vulnerability details about a software component and recommendations to change to a more secured version in a batched manner.
      parameters:
        - name: uuid
          in: header
          description: User Identification uuid
          required: false
          schema:
            type: string
        - name: X-Request-ID
          in: header
          description: Unique id for every CA call
          required: false
          schema:
            type: string
        - name: X-Telemetry-ID
          in: header
          description: Unique RedHat id
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestPackageDetails'

      responses:
        200:
          description: Detailed response for the requested application component batch
          headers:
            uuid:
              schema:
                type: string
              description: User uuid.
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: '#/components/schemas/FreeUserBatch'
                    - $ref: '#/components/schemas/NoVulnerabilities'
              examples:
                FreeUser Batch:
                  $ref: '#/components/examples/free-user-batch'
                No Vulnerability Batch:
                  $ref: '#/components/examples/no-vul-batch'

        401:
          description: Request unauthorized
          content: {}
        404:
          description: Endpoint not found
          content: {}


  /component-vulnerability-analysis/{eco}/{name}/{ver}:
    get:
      tags:
      - CA Singular Call
      summary: Get vulnerability details about a software component and recommendations
        to change to a more secured version
      operationId: da_scanner.api_v3.component-analyses
      parameters:
      - name: eco
        in: path
        description: component ecosystem
        required: true
        schema:
          type: string
      - name: name
        in: path
        description: component name
        required: true
        schema:
          type: string
      - name: ver
        in: path
        description: component version
        required: true
        schema:
          type: string
      - name: uuid
        in: header
        description: User Identification uuid
        required: false
        schema:
          type: string

      responses:
        200:
          description: Detailed response for the requested application component
          headers:
            uuid:
              schema:
                type: string
              description: User uuid.
          content:
            application/json:
              schema:
                items:
                  oneOf:
                    - $ref: '#/components/schemas/FreeUser'
                    - $ref: '#/components/schemas/NoVulnerabilities'
              examples:
                FreeUser:
                  $ref: '#/components/examples/free-user'
                No Vulnerability:
                  $ref: '#/components/examples/no-vul'

        202:
          description: Package is currently Unavailable. Please try again later
          content: {}
        401:
          description: Request unauthorized
          content: {}
        404:
          description: Data not found
          content: {}

components:
  examples:
    higher-rate-3scale:
      value:
        - url: "https://f8a-analytics-2445582058137.production.gw.apicast.io/api/v2/"
        - key: "7e42fa66f65124e6b1266a23431e3d07"
          
    free-user-batch:
      value:
        - package: "django"
          version: "1.1"
          vulnerabilities:
            - id: "SNYK-2010-3082"
              severity: "medium"
              title: "Information Exposure"
              url: "https://snyk.io/vuln/SNYK-PYTHON-DJANGO-40055"
              fixed_in:
                - "1.1.3"
                - "1.2.4"
            - id: "SYNK-2018-1002"
              severity: "medium"
              title: "Information Exposure"
              url: "https://snyk.io/vuln/SNYK-PYTHON-DJANGO-40055"
              fixed_in:
                - "1.1.3"
                - "1.2.4"

        - package: "mango"
          version: "2.1"
          vulnerabilities:
            - id: "SNYK-2010-3082"
              severity: "medium"
              title: "Information Exposure"
              url: "https://snyk.io/vuln/SNYK-PYTHON-DJANGO-40055"
              fixed_in:
                - "1.1.3"
                - "1.2.4"
            - id: "SNYK-2010-3082"
              severity: "medium"
              title: "Information Exposure"
              url: "https://snyk.io/vuln/SNYK-PYTHON-DJANGO-40055"
              fixed_in:
                - "1.1.3"
                - "1.2.4"

    no-vul-batch:
      value:
        - package: "django"
          version: "1.1"
          vulnerabilities: []

    free-user:
      value:
        package: "mango"
        version: "2.1"
        recommendation:
          component_analyses:
            vulnerability:
              - vendor_cve_ids: "SNYK-2018-1002"
              - vendor_cve_ids: "SNYK-2010-3082"
          severity: "high"

    no-vul:
      value:
        package: "mango"
        version: "2.1"
        vulnerabilities: []
  schemas:
    Higher-rate-3scale:
      title: Get higher rate 3-scale token
      type: object
      properties :
        url:
          type: string
          example: "https://f8a-analytics-2445582058137.production.gw.apicast.io/api/v2/"
        key:
          type: string
          example: "7e42fa66f65124e6b1266a23431e3d07"
        
    RequestPackageDetails:
      title: CA Batch Call Request Body
      type: object
      properties:
        ecosystem:
          type: string
          enum:
            - maven
            - pypi
            - npm
        package_versions:
          type: array
          items:
            type: object
            properties:
                package:
                  type: string
                version:
                  type: string
          example:
            - package: django
              version: 1.1
            - package: mango
              version: 2.1

    FreeUserBatch:
      title: Vendor Public Recommendation
      type: object
      properties:
        package:
          type: string
          example: "django"
        version:
          type: string
          example: "1.1"
        recommended_versions:
          type: string
          example: "3.1"
        vulnerability:
          type: array
          items:
            $ref: '#/components/schemas/VulnerabilityDetailsBatch'

    VulnerabilityDetailsBatch:
      title: Vulnerability Details Batch
      description: Information of the vulnerability found
      type: object
      properties:
        id:
          type: string
          example: "SNYK-1234"
        severity:
          type: string
          example: "medium"
        title:
          type: string
          example: "Information Exposure"
        url:
          type: string
          example: "https://snyk.io/vuln/SNYK-PYTHON-DJANGO-40055"
        fixed_in:
          type: array
          items:
            type: string
          example:
            - "1.1.3"
            - "1.2.4"

    VulnerabilityDetails:
      title: Vulnerability Details
      description: Information of the vulnerability found
      type: object
      properties:
        vulnerability:
          type: array
          items:
            type: object
            properties:
              vendor_cve_ids:
                type: string
                example: "SNYK-1234"
              severity:
                type: string
                enum:
                  - low
                  - medium
                  - high
                  - critical
              title:
                type: string
                example: SQL Injection
              url:
                type: string
                example: https://snyk.io/vuln/SNYK-PYTHON-DJANGO-4002
              fixed_in:
                type: array
                items:
                  type: string
                example:
                  - ">=0.19.0-beta.1"

    FreeUser:
      title: Vendor Public Recommendation
      type: object
      properties:
        package:
          type: string
          example: "django"
        version:
          type: string
          example: "1.1"
        recommendation:
          type: object
          properties:
            recommended_version:
              type: string
              example: "3.1"
            component_analyses:
              $ref: '#/components/schemas/VulnerabilityDetails'

    NoVulnerabilities:
      title: No Vulnerability Response
      type: object
      properties:
        package:
          type: string
          example: "django"
        version:
          type: string
          example: "1.1"
        vulnerabilities:
          type: array
          items:
           type: object
          example: []
    
  securitySchemes:
    tokenAuth:
      type: apiKey
      description: 3Scale Token Auth is used for Authentication
      name: user_key
      in: query