openapi: 3.0.1
info:
  title: Analytics Core API Specs for Version 2
  version: "2"
servers:
- url: https://f8a-analytics-2445582058137.production.gw.apicast.io/api/v2
  description: "Dependency Analytics Server"
security:
- tokenAuth: []
paths:
  /component-analyses/:
    post:
      tags:
        - CA batch call
      summary: Get security and other details about a software component and recommendations to change to a more secured version in a batched manner.
      requestBody:
        description: CA Batch Request
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ecosystem:
                  type: string
                  example: pypi
                payload:
                  type: array
                  items:
                    type: object
                    properties:
                      package:
                        type: string
                        example: django
                      version:
                        type: string
                        example: 1.1
              example:
                ecosystem: "pypi"
                payload:
                  - package: "django"
                    version : "1.1"
                  - package: "requests"
                    version : "2.1"

      responses:
        200:
          description: Detailed response for the requested application component batch
          headers:
            uuid:
              schema:
                type: string
              description: User uuid.
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: '#/components/schemas/FreeUser'
                    - $ref: '#/components/schemas/RegisteredUser'
                    - $ref: '#/components/schemas/NoVulnerabilities'
              examples:
                FreeUserBatch:
                  $ref: '#/components/examples/free-user-batch'
                RegisteredUserBatch:
                  $ref: '#/components/examples/registered-user-batch'

  /component-analyses/{eco}/{name}/{ver}:
    get:
      tags:
      - CA Singular Call
      summary: Get security and other details about a software component and recommendations
        to change to a more secured version
      operationId: da_scanner.api_v2.component-analyses
      parameters:
      - name: eco
        in: path
        description: component ecosystem
        required: true
        schema:
          type: string
      - name: name
        in: path
        description: component name
        required: true
        schema:
          type: string
      - name: ver
        in: path
        description: component version
        required: true
        schema:
          type: string
      - name: uuid
        in: header
        description: User Identification uuid
        required: true
        schema:
          type: string

      responses:
        200:
          description: Detailed response for the requested application component
          headers:
            uuid:
              schema:
                type: string
              description: User uuid.
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/RegisteredUser'
                    - $ref: '#/components/schemas/FreeUser'
                    - $ref: '#/components/schemas/NoVulnerabilities'
              examples:
                FreeUser:
                  $ref: '#/components/examples/free-user'
                RegisteredUser:
                  $ref: '#/components/examples/registered-user'

        202:
          description: Package is currently Unavailable. Please try again later
          content: {}
        401:
          description: Request unauthorized
          content: {}
        404:
          description: Data not found
          content: {}

components:
  examples:
    free-user-batch:
      value:
        - recommendation:
            component_analyses:
              vulnerability:
                - vendor_cve_ids: "CVE-2010-3082"
                  cvss: "1.2"
                  is_private: false
                - vendor_cve_ids: "CVE-2018-1002"
                  cvss: "1.3"
                  is_private: false
            recommended_version : "2"
            message: "2 vulnerabilities within this dependency"
            severity: "high"
            public_vulnerabilities_count: 2
            private_vulnerabilities_count: 1
            registeration_link: "https://app.snyk.io/login"

        - recommendation:
            component_analyses:
              vulnerability:
                - vendor_cve_ids: "CVE-2018-1002"
                  cvss: "1.2"
                  is_private: true
                - vendor_cve_ids: "CVE-2010-3082"
                  cvss: "1.3"
                  is_private: false
            recommended_version : "2"
            message: "2 vulnerabilities within this dependency"
            severity: "high"
            public_vulnerabilities_count: 2
            private_vulnerabilities_count: 1
            registeration_link: "https://app.snyk.io/login"

    registered-user-batch:
      value:
        - recommendation:
            component_analyses:
              vulnerability:
                - vendor_cve_ids: "CVE-2018-1002"
                  cvss: "1.2"
                  is_private: true
                - vendor_cve_ids: "CVE-2010-3082"
                  cvss: "1.3"
                  is_private: false
            recommended_version : "2"
            message: "3 vulnerabilities within this dependency, 0 exploitable vulnerabilities"
            severity: "high"
            public_vulnerabilities_count: 2
            private_vulnerabilities_count: 1
            exploitable_vulnerabilities_count: 0
            vendor_package_link: "https://snyk.io/vuln/maven:org.zeroturnaround%3Azt-zip"
        - recommendation:
            component_analyses:
              vulnerability:
                - vendor_cve_ids: "CVE-2018-1002"
                  cvss: "1.2"
                  is_private: true
                - vendor_cve_ids: "CVE-2010-3082"
                  cvss: "1.3"
                  is_private: false
            recommended_version : "2"
            message: "3 vulnerabilities within this dependency, 0 exploitable vulnerabilities"
            severity: "high"
            public_vulnerabilities_count: 2
            private_vulnerabilities_count: 1
            exploitable_vulnerabilities_count: 0
            vendor_package_link: "https://snyk.io/vuln/maven:org.zeroturnaround%3Azt-zip"

    registered-user:
      value:
        recommendation:
          component_analyses:
            vulnerability:
              - vendor_cve_ids: "CVE-2018-1002"
                cvss: "1.2"
                is_private: true
              - vendor_cve_ids: "CVE-2010-3082"
                cvss: "1.3"
                is_private: false
          recommended_version : "2"
          message: "3 vulnerabilities within this dependency, 0 exploitable vulnerabilities"
          severity: "high"
          public_vulnerabilities_count: 2
          private_vulnerabilities_count: 1
          exploitable_vulnerabilities_count: 0
          vendor_package_link: "https://snyk.io/vuln/maven:org.zeroturnaround%3Azt-zip"

    free-user:
      value:
        recommendation:
              component_analyses:
                vulnerability:
                  - vendor_cve_ids: "CVE-2018-1002"
                    cvss: "1.2"
                    is_private: true
                  - vendor_cve_ids: "CVE-2010-3082"
                    cvss: "1.3"
                    is_private: false
              recommended_version : "2"
              message: "2 vulnerabilities within this dependency"
              severity: "high"
              public_vulnerabilities_count: 2
              private_vulnerabilities_count: 1
              registeration_link: "https://app.snyk.io/login"

  schemas:
    VulnerabilityDetails:
      title: Vulnerability Details
      description: Information of the vulnerability found
      type: object
      properties:
        vulnerability:
          type: array
          items:
            type: object
            properties:
              vendor_cve_ids:
                type: string
                example: "CVE-1234"
              cvss:
                type: string
                example: 9.2
              is_private:
                type: boolean
                example: true

    RegisteredUser:
      title: Vendor Private Recommendation
      type: object
      properties:
        recommendation:
          type: object
          properties:
            recommended_version:
              type: string
              example: 2
            component_analyses:
              $ref: '#/components/schemas/VulnerabilityDetails'
            message:
              type: string
              example: "3 vulnerabilities within this dependency, 0 exploitable vulnerabilities"
            severity:
              type: string
              example: "high"
            public_vulnerabilities_count:
              type: integer
              example: 0
            private_vulnerabilities_count:
              type: integer
              example: 0
            exploitable_vulnerabilities_count:
              type: integer
              example: 0
            vendor_package_link:
              type: string
              example : "https://snyk.io/vuln/maven:org.webjars%3Ajquery-form"

    FreeUser:
      title: Vendor Public Recommendation
      type: object
      properties:
        recommendation:
          type: object
          properties:
            recommended_version:
              type: string
              example: "3.1"
            component_analyses:
              $ref: '#/components/schemas/VulnerabilityDetails'
            message:
              type: string
              example: "3 vulnerabilities within this dependency, 0 exploitable vulnerabilities"
            severity:
              type: string
              example: "high"
            public_vulnerabilities_count:
              type: integer
              example: 1
            private_vulnerabilities_count:
              type: integer
              example: 1
            registeration_link:
              type: string
              example : "https://app.snyk.io/login"

    NoVulnerabilities:
      title: No Vulnerability Response
      type: object
      properties:
        recommendation:
          type: object
          example: {}

  securitySchemes:
    tokenAuth:
      type: apiKey
      description: 3Scale Token Auth is used for Authentication
      name: user_key
      in: query